# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    filter:
        class: AppBundle\Service\ImportRuleService

    converter:
        class: AppBundle\Service\ValueConverterService

    mapping:
        class: AppBundle\Service\MappingService


    doctrine.writer.factory:
       class: AppBundle\Service\DoctrineWriterFactory
       arguments:
           - '@doctrine.orm.entity_manager'

    csv.reader.factory:
        class: Port\Csv\CsvReaderFactory
        arguments:
            - 0

    workflow.organizer:
        class: AppBundle\Service\WorkflowOrganizer
        arguments:
            - '@filter'
            - '@converter'
            - '@mapping'
            - '@csv.reader.factory'
            - '@doctrine.writer.factory'